[omnetpp-wasm-build]

# preloaded files
ned-folders = [
	"./networks",
	"./channels",
	"./modules"
]
images = [
	"./images@./quisp/images"
]
ini-file = "./wasm.ini"
project-folder = "./quisp"
output-folder = "./wasm-out"
exec-args =  [
	"--image-path=/quisp/images"
]
