name: quisp main
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    container:
      image: omnetpp/omnetpp:u18.04-5.6.2
    steps:
      - name: Install the latest git and dependencies
        run: |
          apt-get update -y
          apt-get install -y --no-install-recommends software-properties-common gpg-agent cmake g++
          add-apt-repository ppa:git-core/ppa
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
          apt-get update -y
          apt install clang-format-12 clang-tidy-12 lldb-12 git lcov -y
          ln -s /usr/bin/clang-format-12 /usr/bin/clang-format
          ln -s /usr/bin/clang-tidy-12 /usr/bin/clang-tidy
          ln -sf /usr/bin/clang-12 /usr/bin/clang
          ln -sf /usr/bin/clang++-12 /usr/bin/clang++
          ln -sf /usr/bin/llvm-profdata-12 /usr/bin/llvm-profdata
          ln -sf /usr/bin/llvm-cov-12 /usr/bin/llvm-cov
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v3
      - name: make eigen
        run: make eigen
      - name: generate makefile
        run: make makefile-lib
      - name: generate message headers
        run: make msgheaders
      - name: clang-format
        run: make format-ci
      - name: make googletest
        run: make googletest
      - name: clang-tidy
        run: make tidy
      - name: unit tests and generate coverage report
        run: |
          opp_makemake -f --deep -O out -i ./makefrag -M release --make-so
          make lcov.info
          lcov -r lcov.info 'googletest/*' -o lcov_filtered.info
        working-directory: quisp
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./quisp/lcov_filtered.info
      # - name: module tests
      # run: make run-module-test
      - name: Run Simulations
        run: /bin/bash test.sh
        working-directory: test
      - name: Check Simulation Results
        run: python -m unittest discover
        working-directory: test
